export default [
	'Wokeuplikerick',
	'Rockism',
	'Party\'s Over',
	'One Night Enemy Stand',
	'The Plot Thickens',
	'Building Genders',
	'Charmed, I\'m Sure (Underwater Mix)',
	'Chase Your Nightmares',
	'Tease and Denial',
	'Star-Lord',
	'Cross Faded',
	'J&M',
	'Boy Problems',
	'WWW (Edit)',
	'Nevertheless',
	'Affair of the Diamond Necklace',
	'Carpal Tunnel',
];
